import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'apikey, authorization, x-client-info, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function admin(){const raw=Deno.env.get('SUPABASE_SECRET_KEYS')||'{}';let keys:Record<string,string>={};try{keys=JSON.parse(raw)}catch{}const key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('VAP server credentials are not configured.');return createClient(Deno.env.get('SUPABASE_URL')!,key);}
function label(t:string){return t==='chrome'?'Chrome':t==='mobile'?'Mobile':'PC';}
function titleFrom(msg:string){return msg.replace(/^\s*(hey\s+)?vap\s*[,!:.-]?\s*/i,'').trim().replace(/^please\s+/i,'').replace(/^(create|add|make)\s+(a\s+)?(new\s+)?task\s*(to|for)?\s*/i,'').replace(/^(remind|reminder)\s+(me\s+)?(to|about)?\s*/i,'').trim()||'VAP task';}
function taskIntent(m:string){return /\b(create|add|make)\b.{0,25}\b(task|todo|to-do)\b/i.test(m);}
function reminderIntent(m:string){return /\b(remind|reminder)\b/i.test(m);}
function nextChrome(m:string){return reminderIntent(m)&&/(next|when|whenever).{0,60}(open|start|launch).{0,40}(chrome|browser)/i.test(m);}
function simpleDueDate(m:string){const now=new Date();if(/\btoday\b/i.test(m))return now.toISOString().slice(0,10);if(/\btomorrow\b/i.test(m)){now.setDate(now.getDate()+1);return now.toISOString().slice(0,10);}return null;}
function geminiKey(){return Deno.env.get('GEMINI_API_KEY')||Deno.env.get('GOOGLE_AI_API_KEY')||'';}
function models(){return(Deno.env.get('VAP_GEMINI_MODELS')||'gemini-3.8-flash,gemini-3.7-flash,gemini-3.6-flash').split(',').map(x=>x.trim()).filter(Boolean);}
async function ai(prompt:string){const key=geminiKey();if(!key)throw new Error('VAP AI key is not configured on the server.');let last='';for(const model of models()){try{const c=new AbortController();const t=setTimeout(()=>c.abort(),5000);const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:900,thinkingConfig:{thinkingLevel:'low'}}}),signal:c.signal});clearTimeout(t);const raw=await r.text();if(!r.ok){last=`${model}: HTTP ${r.status}`;if([429,500,502,503,504].includes(r.status))continue;break;}const d=JSON.parse(raw);const text=(d?.candidates?.[0]?.content?.parts||[]).map((p:any)=>p?.text||'').join('').trim();if(text)return{answer:text,model};last=`${model}: empty response`;}catch(e){last=e instanceof Error?e.message:String(e);}}throw new Error(`VAP AI is temporarily unavailable. ${last}`);}
function wantsPage(md:any,msg:string){return String(md?.mode||'chat')!=='chat'||/\b(this page|current page|this website|this site|selected text|on this page|from this page)\b/i.test(msg);}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const b=await req.json();const kind=String(b.kind||'event');
if(kind==='pair'){const code=String(b.pairingCode||'').trim();if(!code)return json({error:'Missing VAP pairing code.'},400);const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(code));const pairingHash=Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('');const db=admin();const{data:p,error:pe}=await db.from('vertex_pa_device_pairings').select('*').eq('pairing_hash',pairingHash).is('used_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(pe)throw pe;if(!p)return json({error:'VAP pairing code is invalid or expired.'},401);const token=`vap_${crypto.randomUUID().replace(/-/g,'')}${crypto.randomUUID().replace(/-/g,'')}`;const{data:existing}=await db.from('vertex_pa_devices').select('id').eq('user_id',p.user_id).eq('device_name',p.device_name).eq('device_type',p.device_type).maybeSingle();let deviceId=existing?.id;if(deviceId)await db.from('vertex_pa_devices').update({device_token:token,status:'online',last_seen:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',deviceId);else{const{data:created,error}=await db.from('vertex_pa_devices').insert({user_id:p.user_id,device_name:p.device_name,device_type:p.device_type,device_token:token,status:'online',last_seen:new Date().toISOString()}).select('id').single();if(error)throw error;deviceId=created.id;}await db.from('vertex_pa_device_pairings').update({used_at:new Date().toISOString()}).eq('id',p.id);return json({ok:true,deviceToken:token,deviceId,deviceName:p.device_name});}
const token=String(b.deviceToken||'').trim();if(!token)return json({error:'Missing device token.'},401);const db=admin();const{data:d,error:de}=await db.from('vertex_pa_devices').select('*').eq('device_token',token).maybeSingle();if(de)throw de;if(!d)return json({error:'Unknown VAP device.'},401);const now=new Date().toISOString();const msg=String(b.message||'').trim();const md:Record<string,unknown>=typeof b.metadata==='object'&&b.metadata?b.metadata:{};
await db.from('vertex_pa_devices').update({status:String(b.status||'online'),last_seen:now,last_event:msg||kind,metadata:md,updated_at:now}).eq('id',d.id);
if(kind==='heartbeat')return json({ok:true,device:{id:d.id,name:d.device_name,status:'online',last_seen:now}});
if(kind==='event'){await db.from('vertex_pa_activity').insert({user_id:d.user_id,action:`${label(d.device_type)} • ${msg||'Device event'}`,description:msg||'VAP branch event',metadata:{device_id:d.id,...md}});return json({ok:true});}
if(kind==='poll_actions'){const{data:acts,error}=await db.from('vertex_pa_actions').select('*').eq('user_id',d.user_id).eq('status','queued').or(`target_device_id.eq.${d.id},target_device_id.is.null`).order('created_at',{ascending:true}).limit(10);if(error)throw error;const list=acts||[];if(list.length)await db.from('vertex_pa_actions').update({status:'running',claimed_at:now,updated_at:now}).in('id',list.map((x:any)=>x.id));return json({ok:true,actions:list});}
if(kind==='complete_action'){const id=String(md.action_id||'');const st=['completed','failed','cancelled','awaiting_confirmation'].includes(String(md.action_status))?String(md.action_status):'failed';await db.from('vertex_pa_actions').update({status:st,result:typeof md.result==='object'?md.result:{value:md.result||''},error:st==='failed'?(typeof md.result==='object'?(md.result as any)?.error:String(md.result||'')):null,completed_at:['completed','failed'].includes(st)?now:null,updated_at:now}).eq('id',id).eq('user_id',d.user_id);return json({ok:true});}
if(kind==='ack_reminder'){const id=String(md.reminder_id||'');if(id)await db.from('vertex_pa_reminders').update({status:'Completed',updated_at:now}).eq('id',id).eq('user_id',d.user_id);return json({ok:true});}
if(kind==='startup'){const{data:r,error}=await db.from('vertex_pa_reminders').select('id,title,remind_at,status').eq('user_id',d.user_id).eq('status','Pending').like('title','__VAP_CHROME_OPEN__:%').order('created_at',{ascending:true}).limit(10);if(error)throw error;return json({ok:true,reminders:(r||[]).map((x:any)=>({id:x.id,title:String(x.title).replace(/^__VAP_CHROME_OPEN__:\s*/i,''),remind_at:x.remind_at}))});}
if(kind==='vault_save'){const title=String(md.title||d.device_name||'Saved from Chrome').slice(0,240);const url=String(md.url||'').trim();const category=String(md.category||'random ideas').slice(0,80);const note=String(md.note||msg||'').slice(0,4000);const pageText=String(md.pageText||'').slice(0,12000);const{data:item,error}=await db.from('vertex_pa_vault_items').insert({user_id:d.user_id,title,url:url||null,category,source_type:'chrome',note,page_text:pageText,metadata:{device_id:d.id,selectionText:String(md.selectionText||'').slice(0,4000)}}).select('id,title,url,category,created_at').single();if(error)throw error;await db.from('vertex_pa_activity').insert({user_id:d.user_id,action:'Chrome • Vault saved',description:title,metadata:{device_id:d.id,vault_id:item.id}});return json({ok:true,answer:`Saved to VAP Vault: ${title}`,item});}
if(kind==='ask'){
 if(nextChrome(msg)){const title=titleFrom(msg);const{data:e}=await db.from('vertex_pa_reminders').select('id').eq('user_id',d.user_id).eq('status','Pending').eq('title',`__VAP_CHROME_OPEN__: ${title}`).limit(1);if(!e?.length)await db.from('vertex_pa_reminders').insert({user_id:d.user_id,title:`__VAP_CHROME_OPEN__: ${title}`,remind_at:now,status:'Pending'});return json({ok:true,answer:`Done. I’ll remind you the next time VAP starts in Chrome: ${title}`});}
 if(taskIntent(msg)){const title=titleFrom(msg);const due=simpleDueDate(msg);const{data:t,error}=await db.from('vertex_pa_tasks').insert({user_id:d.user_id,title,description:msg,priority:'Medium',status:'To Do',due_date:due}).select('id,title,due_date').single();if(error)throw error;return json({ok:true,answer:`Done. I created the central VAP task: ${title}${due?` (due ${due})`:''}.`,task:t});}
 if(reminderIntent(msg)){const due=simpleDueDate(msg);if(due){const at=new Date(`${due}T09:00:00.000Z`).toISOString();const title=titleFrom(msg);const{data:r,error}=await db.from('vertex_pa_reminders').insert({user_id:d.user_id,title,remind_at:at,status:'Pending'}).select('id,title,remind_at').single();if(error)throw error;return json({ok:true,answer:`Done. I saved the reminder centrally for ${due}: ${title}`,reminder:r});}}
 if(/\b(open|launch|start)\b.{0,40}\b(canva|higgsfield|instagram|whatsapp|gmail)\b/i.test(msg)){const site=/canva/i.test(msg)?'https://www.canva.com/':/higgsfield/i.test(msg)?'https://higgsfield.ai/':/instagram/i.test(msg)?'https://www.instagram.com/':/whatsapp/i.test(msg)?'https://web.whatsapp.com/':'https://mail.google.com/';const{data:a,error}=await db.from('vertex_pa_actions').insert({user_id:d.user_id,source_device_id:d.id,action_type:'open_url',payload:{url:site,instruction:msg},requires_confirmation:true,status:'queued'}).select('*').single();if(error)throw error;return json({ok:true,answer:`Queued ${site} for the authorized VAP branch.`,action:a});}
 const page=wantsPage(md,msg);const prompt=`You are VAP, the user's personal JARVIS and central operating assistant. Be fast, concise, accurate, practical and honest. Challenge weak assumptions respectfully. Never claim an external action completed unless a device confirms it. Current mode: ${String(md.mode||'chat')}. User request: ${msg}. ${page?`Page title: ${String(md.title||'')}\nURL: ${String(md.url||'')}\nSelection: ${String(md.selectionText||'').slice(0,2500)}\nPage text: ${String(md.pageText||'').slice(0,7000)}`:'No page context.'}`;const result=await ai(prompt);return json({ok:true,answer:result.answer,model:result.model});}
return json({error:'Unknown request kind.'},400);
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'VAP device error.'},500);}});
