const $=id=>document.getElementById(id);
let currentContext=null, recognition=null, isListening=false, wakeListening=false, sketchData="";
let config={autoSpeak:true,notificationsEnabled:true,automationMode:"ask",conversationId:"",wakeMode:false,wakePhrase:"vap",proactiveMode:true,actionPolling:true};

document.addEventListener("DOMContentLoaded",init);
async function init(){ bindEvents(); await loadSettings(); await loadPendingAction(); await refreshContext(); await sendBackground({type:"STARTUP_REMINDERS"}); setState("IDLE","Ready"); }
function bindEvents(){
  $("askForm").addEventListener("submit",e=>{e.preventDefault(); const t=$("message").value.trim(); if(t) sendMessage(t);});
  $("message").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault(); const t=$("message").value.trim(); if(t) sendMessage(t);}});
  $("pageButton").addEventListener("click",async()=>{await refreshContext(); addBubble("system","Current webpage context loaded.");});
  $("refreshContext").addEventListener("click",refreshContext); $("savePage").addEventListener("click",saveCurrentPage);
  $("micButton").addEventListener("click",toggleVoice); $("wakeButton").addEventListener("click",toggleWakeMode);
  $("newConversation").addEventListener("click",newConversation); $("todayButton").addEventListener("click",()=>sendMessage("Give me my VAP Today brief: priorities, tasks, reminders, active projects and what I should do next."));
  $("modeSelect").addEventListener("change",()=>addBubble("system",`Mode set to ${$("modeSelect").selectedOptions[0].text}.`));
  document.querySelectorAll("[data-quick]").forEach(b=>b.addEventListener("click",()=>sendMessage(b.dataset.quick)));
  $("settingsButton").addEventListener("click",()=>$("settings").classList.remove("hidden")); $("closeSettings").addEventListener("click",()=>$("settings").classList.add("hidden"));
  $("saveSettings").addEventListener("click",saveSettings); $("checkNow").addEventListener("click",checkNow);
  document.querySelectorAll(".permission-button").forEach(b=>b.addEventListener("click",async()=>{const r=await sendBackground({type:"REQUEST_SITE_PERMISSION",site:b.dataset.permission}); if(r.ok&&r.result?.granted){b.classList.add("granted");b.textContent=b.textContent.replace(" ✓","")+" ✓";$("permissionStatus").textContent=`${b.dataset.permission} permission granted.`;}else $("permissionStatus").textContent=r.error||"Permission was not granted.";}));
  $("sketchButton").addEventListener("click",openSketch); $("closeSketch").addEventListener("click",closeSketch); $("clearSketch").addEventListener("click",clearSketch); $("useSketch").addEventListener("click",useSketch);
  initCanvas();
}
async function loadSettings(){const r=await sendBackground({type:"GET_CONFIG"}); if(!r.ok)return; config={...config,...r.result}; $("deviceName").value=config.deviceName||"VAP Chrome";$("deviceToken").value=config.deviceToken||"";$("pairingCode").value=config.pairingCode||"";$("notificationsEnabled").checked=config.notificationsEnabled!==false;$("autoSpeak").checked=config.autoSpeak!==false;$("proactiveMode").checked=config.proactiveMode!==false;$("actionPolling").checked=config.actionPolling!==false;$("wakeMode").checked=config.wakeMode===true;$("wakePhrase").value=config.wakePhrase||"vap";$("automationMode").value=config.automationMode||"ask"; await refreshPermissionButtons(); setConnection(config.deviceToken?"CONNECTED":"SETUP"); }
async function saveSettings(){const token=$("deviceToken").value.trim(); const pairingCode=$("pairingCode").value.trim(); if(!token && !pairingCode){$("settingsResult").textContent="Enter a one-time pairing code or an existing private device token.";return;} const next={deviceToken:token,pairingCode,deviceName:$("deviceName").value.trim()||"VAP Chrome",notificationsEnabled:$("notificationsEnabled").checked,autoSpeak:$("autoSpeak").checked,proactiveMode:$("proactiveMode").checked,actionPolling:$("actionPolling").checked,wakeMode:$("wakeMode").checked,wakePhrase:$("wakePhrase").value.trim().toLowerCase()||"vap",automationMode:$("automationMode").value,conversationId:config.conversationId||""}; const r=await sendBackground({type:"SAVE_CONFIG",...next}); if(r.ok){config={...config,...next};$("settingsResult").textContent=pairingCode?"Pairing code saved. VAP will connect automatically on the next request.":"Saved.";setConnection(pairingCode&&!token?"PAIRING":"CONNECTED");if(config.wakeMode) startWakeRecognition();}else $("settingsResult").textContent=r.error||"Could not save.";}
async function loadPendingAction(){const r=await sendBackground({type:"GET_PENDING_ACTION"});if(!r.ok||!r.result)return;currentContext=r.result.context||null;renderContext();if(r.result.type==="save")$("message").value="Save this to my VAP Vault. Remember why I found it useful: ";else if(r.result.type==="think")$("message").value="Think deeply about this page and tell me what matters, why it matters, and what I should do next.";else $("message").value="Analyze this webpage for me.";$("message").focus();}

async function saveCurrentPage(){
  if(!currentContext) await refreshContext();
  if(!currentContext?.url){addBubble("vap error","No webpage context is available to save.");return;}
  const note=window.prompt("Why is this useful? (optional)","") ?? "";
  const r=await sendBackground({type:"SAVE_VAULT",metadata:{title:currentContext.title,url:currentContext.url,pageText:currentContext.pageText,selectionText:currentContext.selectionText,note,category:"random ideas"}});
  if(r.ok){addBubble("vap","Saved to VAP Vault: "+(r.result?.item?.title||currentContext.title));}else addBubble("vap error",r.error||"Could not save to VAP Vault.");
}
async function prepareAction(type){await refreshContext();$("message").value=type==="save"?"Save this to my VAP Vault. Remember why I found it useful: ":"Think deeply about this page and tell me what matters and what I should do next.";$("message").focus();}
async function refreshContext(){const r=await sendBackground({type:"GET_ACTIVE_CONTEXT"});if(!r.ok){currentContext=null;renderContext();return;}currentContext=r.result;renderContext();}
function renderContext(){const c=currentContext;$("pageTitle").textContent=c?.title||"No page context loaded";$("pageUrl").textContent=c?.url||"";$("selectionBadge").classList.toggle("hidden",!c?.selectionText);$("contextSource").textContent=c?"Captured on demand":"On demand only";}
async function sendMessage(text,interaction=null){const mode=$("modeSelect").value; addBubble("user",text);$("message").value="";setState("THINKING",`VAP is thinking in ${mode} mode…`);let metadata=currentContext?sanitizeContext(currentContext):{};metadata.interaction=interaction?.interaction||"text";metadata.mode=mode;metadata.automationMode=config.automationMode||"ask";metadata.conversationId=config.conversationId||"";metadata.sketch=sketchData||undefined;try{const r=await sendBackground({type:"ASK_VAP",message:text,metadata});if(!r.ok){addBubble("vap error",r.error||"VAP request failed.");setState("ERROR","Request failed");return;}if(r.result?.conversationId){config.conversationId=r.result.conversationId;await chrome.storage.local.set({conversationId:config.conversationId});}const answer=r.result?.answer;if(typeof answer!=="string"){addBubble("vap error","VAP returned no answer.");setState("ERROR","Invalid response");return;}addBubble("vap",answer);if(config.autoSpeak!==false){setState("SPEAKING","VAP is speaking…");await speak(answer);}setState("IDLE","Ready");sketchData="";}catch(e){addBubble("vap error",e.message||String(e));setState("ERROR","Unexpected error");}}
function sanitizeContext(c){return{url:c.url||"",title:c.title||"",pageText:String(c.pageText||"").slice(0,12000),selectionText:String(c.selectionText||"").slice(0,4000),branch:"chrome"};}
function addBubble(kind,text){const b=document.createElement("div");b.className=`bubble ${kind}`;b.textContent=text;$("conversation").appendChild(b);b.scrollIntoView({behavior:"smooth",block:"nearest"});}
function setState(s,t){$("state").textContent=s;$("statusText").textContent=t;$("orb").className=`orb ${s.toLowerCase()}`;}
function setupRecognition({wake=false}={}){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return null;const r=new SR();r.lang=navigator.language||"en-IN";r.continuous=wake;r.interimResults=true;r.maxAlternatives=1;r.onstart=()=>{if(wake){wakeListening=true;setState("LISTENING","Wake mode active while VAP is open…");}else{isListening=true;setState("LISTENING","Listening…");}};r.onresult=async e=>{let tr="";for(let i=e.resultIndex;i<e.results.length;i++)tr+=e.results[i][0].transcript;tr=tr.trim();if(wake){const phrase=(config.wakePhrase||"vap").toLowerCase();const low=tr.toLowerCase();if(low.includes(phrase)){const rest=tr.slice(low.indexOf(phrase)+phrase.length).trim();if(rest){r.stop();wakeListening=false;await sendMessage(rest,{interaction:"wake-word"});}else setState("LISTENING","VAP heard you. Say the command…");}}else $("message").value=tr;};r.onerror=e=>{if(wake){wakeListening=false;setState("IDLE",`Wake mode paused: ${e.error||"voice error"}`);}else{isListening=false;setState("ERROR",`Voice error: ${e.error||"unknown"}`);}};r.onend=async()=>{if(wake&&config.wakeMode){wakeListening=false;setTimeout(()=>{if(config.wakeMode&&!wakeListening)startWakeRecognition();},700);}else{isListening=false;const t=$("message").value.trim();if(t)await sendMessage(t,{interaction:"voice"});else setState("IDLE","Ready");}};return r;}
async function toggleVoice(){if(isListening&&recognition){recognition.stop();return;}recognition=setupRecognition();if(!recognition){addBubble("vap error","Speech recognition is unavailable in this Chrome build. Text mode still works.");return;}try{recognition.start();}catch(e){setState("ERROR",e.message||"Could not start microphone.");}}
function toggleWakeMode(){config.wakeMode=!config.wakeMode;$("wakeMode").checked=config.wakeMode;if(config.wakeMode){startWakeRecognition();addBubble("system","Wake mode is active only while the VAP panel is open. Chrome will show microphone activity.");}else{if(recognition&&wakeListening)recognition.stop();wakeListening=false;setState("IDLE","Wake mode off");}chrome.storage.local.set({wakeMode:config.wakeMode});}
function startWakeRecognition(){if(!config.wakeMode||wakeListening)return;recognition=setupRecognition({wake:true});if(!recognition){addBubble("vap error","Wake mode is unavailable in this Chrome build.");return;}try{recognition.start();}catch(e){console.warn(e);}}
async function newConversation(){await sendBackground({type:"NEW_CONVERSATION"});config.conversationId="";$("conversation").innerHTML="";addBubble("system","New conversation. Central VAP memory, tasks, projects and reminders remain intact.");}
async function checkNow(){setConnection("CHECKING");const r=await sendBackground({type:"HEARTBEAT",metadata:{branch:"chrome",reason:"manual check"}});setConnection(r.ok?"CONNECTED":"OFFLINE");$("settingsResult").textContent=r.ok?"VAP is reachable.":"VAP could not be reached: "+(r.error||"unknown error");}
function speak(text){return new Promise(resolve=>{if(!("speechSynthesis"in window))return resolve();speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=navigator.language||"en-IN";u.rate=1;u.pitch=1;u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u);});}
function sendBackground(m){return new Promise(resolve=>chrome.runtime.sendMessage(m,resolve));}
async function refreshPermissionButtons(){const r=await sendBackground({type:"GET_SITE_PERMISSIONS"});if(!r.ok)return;for(const b of document.querySelectorAll(".permission-button")){if(r.result?.[b.dataset.permission]){b.classList.add("granted");if(!b.textContent.endsWith(" ✓"))b.textContent+=" ✓";}}}
function setConnection(t){$("connectionBadge").textContent=t;}
function openSketch(){$("sketchModal").classList.remove("hidden");resizeCanvas();}
function closeSketch(){$("sketchModal").classList.add("hidden");}
function clearSketch(){const c=$("sketchCanvas"),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);}
function useSketch(){const c=$("sketchCanvas");sketchData=c.toDataURL("image/png",0.72);$("message").value="Use this sketch as my idea. Interpret what I am trying to build and suggest the best next step.";closeSketch();addBubble("system","Sketch attached to the next VAP request.");$("message").focus();}
function initCanvas(){const c=$("sketchCanvas");let down=false,last=null;const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};};c.addEventListener("pointerdown",e=>{down=true;last=pos(e);c.setPointerCapture(e.pointerId);});c.addEventListener("pointermove",e=>{if(!down)return;const p=pos(e),x=c.getContext("2d");x.beginPath();x.moveTo(last.x,last.y);x.lineTo(p.x,p.y);x.strokeStyle="#fff";x.lineWidth=5;x.lineCap="round";x.stroke();last=p;});c.addEventListener("pointerup",()=>{down=false;});}
function resizeCanvas(){const c=$("sketchCanvas");c.style.touchAction="none";}
