import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'apikey, authorization, x-client-info, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
function admin(){const raw=Deno.env.get('SUPABASE_SECRET_KEYS')||'{}';let keys:Record<string,string>={};try{keys=JSON.parse(raw)}catch{}const key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw new Error('VAP server credentials are not configured.');return createClient(Deno.env.get('SUPABASE_URL')!,key);}
function clean(s:string){return s.replace(/^\s*(hey\s+)?vap\s*[,!:.\-]?\s*/i,'').trim();}
function intent(s:string){const x=s.toLowerCase();return /\b(create|make|build|design|generate|prepare|plan|publish|upload|post|automate|setup|set up|organize|research)\b/.test(x)||/social media|campaign|workflow|automation|all my projects|upload.*website|n8n/.test(x);}
function plan(goal:string){const x=goal.toLowerCase(),steps:any[]=[];if(/social media|campaign/.test(x)){steps.push({title:'Plan campaign',action_type:'analyze_goal',payload:{goal}});steps.push({title:'Create campaign creative',action_type:'generate_creative',payload:{goal,preferred_tools:['Canva','Higgsfield']}});steps.push({title:'Generate social captions',action_type:'generate_caption',payload:{goal,channels:['Instagram','LinkedIn']}});steps.push({title:'Review and prepare publishing',action_type:'publish_social',payload:{goal}});}else if(/n8n|workflow|automation/.test(x)){steps.push({title:'Design automation workflow',action_type:'create_workflow',payload:{goal,preferred_tool:'n8n'}});}else if(/upload.*website|all my projects|vertex web/.test(x)){steps.push({title:'Prepare VERTEX website project updates',action_type:'update_vertex_website',payload:{goal,site:'https://vertex-kre8.netlify.app/'}});}else steps.push({title:'Analyze goal and recommend next action',action_type:'analyze_goal',payload:{goal}});return steps;}
function geminiKey(){return Deno.env.get('GEMINI_API_KEY')||Deno.env.get('GOOGLE_AI_API_KEY')||'';}
async function generate(prompt:string){const key=geminiKey();if(!key)throw new Error('GEMINI_API_KEY is not configured.');for(const model of (Deno.env.get('VAP_GEMINI_MODELS')||'gemini-3.8-flash,gemini-3.7-flash,gemini-3.6-flash').split(',').map(x=>x.trim()).filter(Boolean)){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:1200,thinkingConfig:{thinkingLevel:'low'}}}),signal:c.signal});clearTimeout(t);const raw=await r.text();if(!r.ok){if([429,500,502,503,504].includes(r.status))continue;throw new Error(`Gemini HTTP ${r.status}`);}const d=JSON.parse(raw);const text=(d?.candidates?.[0]?.content?.parts||[]).map((p:any)=>p?.text||'').join('').trim();if(text)return text;}catch(e){if(e instanceof Error && /HTTP 4(?!29)/.test(e.message))throw e;}}throw new Error('AI generation unavailable.');}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const b=await req.json();const token=String(b.deviceToken||'').trim();if(!token)return json({error:'VAP device token is not configured.'},401);const db=admin();const{data:d,error:de}=await db.from('vertex_pa_devices').select('id,user_id,device_name,device_type').eq('device_token',token).maybeSingle();if(de)throw de;if(!d)return json({error:'Invalid VAP device token.'},401);const goal=clean(String(b.message||''));if(!goal)return json({error:'Mission goal is required.'},400);if(!intent(goal))return json({error:'This request does not require a mission.'},400);const mode=String(b.metadata?.mode||'execute'),steps=plan(goal);const{data:mission,error:me}=await db.from('vertex_pa_missions').insert({user_id:d.user_id,source_device_id:d.id,title:goal.slice(0,120),goal,status:'ready',mode,current_step:0,progress:0}).select().single();if(me)throw me;const created:any[]=[];
for(let i=0;i<steps.length;i++){const s=steps[i];let status='pending',result:any={},actionId:string|null=null;
 if(s.action_type==='generate_caption'){try{result={text:await generate(`Create polished but concise social captions for VERTEX kre8, a Creative Intelligence Company. Goal: ${goal}. Produce one Instagram caption and one LinkedIn caption. No fake claims, metrics or testimonials. Use the positioning “Where Creativity Meets Intelligence.”`)};status='completed';}catch(e){result={error:e instanceof Error?e.message:String(e)};status='failed';}}
 else if(s.action_type==='create_workflow'){try{result={workflow:await generate(`Design an n8n automation workflow for this request: ${goal}. Return practical workflow steps and a compact JSON-like node outline. Do not claim it was deployed. Clearly list required credentials/integrations and where human approval is needed.`)};status='completed';}catch(e){result={error:e instanceof Error?e.message:String(e)};status='failed';}}
 else if(s.action_type==='analyze_goal'){try{result={analysis:await generate(`Analyze this VAP mission for a founder: ${goal}. Identify objective, assumptions, dependencies, best next action and risks. Be concise. Do not invent facts.`)};status='completed';}catch(e){result={note:'Analysis will be completed by the VAP brain.'};}}
 else {const url=s.action_type==='generate_creative'?'https://www.canva.com/':s.action_type==='publish_social'?'https://www.instagram.com/':'https://vertex-kre8.netlify.app/';const requires=s.action_type==='publish_social'||mode!=='auto';const{data:a,error}=await db.from('vertex_pa_actions').insert({user_id:d.user_id,source_device_id:d.id,action_type:'site_task',payload:{url,instruction:s.action_type==='generate_creative'?`Open Canva and prepare the requested VERTEX campaign creative: ${goal}. Use the VERTEX brand system and do not publish.`:s.action_type==='publish_social'?`Prepare the social post for: ${goal}. Do not publish until the user confirms.`:`Prepare the VERTEX website update requested by: ${goal}.`,mission_id:mission.id,step_id:null},requires_confirmation:requires,status:'queued'}).select('id').single();if(error)throw error;actionId=a.id;status=requires?'awaiting_confirmation':'pending';}
 const{data:step,error:se}=await db.from('vertex_pa_mission_steps').insert({mission_id:mission.id,step_index:i,title:s.title,action_type:s.action_type,payload:s.payload,status,result,action_id:actionId}).select().single();if(se)throw se;created.push(step);if(actionId&&step?.id)await db.from('vertex_pa_actions').update({payload:{...((s.payload||{}) as Record<string,unknown>),mission_id:mission.id,step_id:step.id}}).eq('id',actionId);
 if(status==='completed'||status==='failed') await db.from('vertex_pa_missions').update({current_step:i+1,progress:Math.round(((i+1)/steps.length)*100),status:status==='failed'?'failed':i===steps.length-1?'completed':'running',result:result,updated_at:new Date().toISOString(),completed_at:i===steps.length-1?new Date().toISOString():null}).eq('id',mission.id);
}
const waiting=created.some((x:any)=>x.status==='awaiting_confirmation');if(waiting)await db.from('vertex_pa_missions').update({status:'awaiting_confirmation',updated_at:new Date().toISOString()}).eq('id',mission.id);
await db.from('vertex_pa_activity').insert({user_id:d.user_id,action:'Mission created',description:goal,metadata:{mission_id:mission.id,device_id:d.id,step_count:created.length}});
return json({ok:true,mission,steps:created,message:`Mission created on VAP Central with ${created.length} step(s).`});
}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'VAP mission request failed.'},500);}});
